name: Deploy Lambda Function

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  LAMBDA_FUNCTION_NAME: normal
  AWS_ROLE_TO_ASSUME: arn:aws:iam::140023404662:role/normal-role-efqu9sk5

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy Lambda
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install AWS CLI
        run: pip install awscli

      - name: Run unit tests
        run: python -m unittest discover -s . -p 'test_*.py'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ env.AWS_ROLE_TO_ASSUME }}
          role-session-name: GitHubActionsLambdaDeployment
