name: Deploy Lambda Function

on:
  push:
    branches:
      - main

env:
  AWS_REGION: eu-central-1
  LAMBDA_FUNCTION_NAME: twentyfour

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy Lambda
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install AWS CLI
        run: pip install awscli

      - name: Run unit tests
        run: python -m unittest discover -s . -p 'test_*.py'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Zip Lambda function
        run: zip function.zip lambda_function.py

      # (Add deploy logic here, like aws lambda update-function-code...)
